language: csharp
dist: trusty
env:
  STEELTOE_VERSION: 2.1.0
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
dotnet: 2.0.3
os:
  - linux
  - osx
osx_image: xcode8.3
branches:
  only:
    - master
    - dev
    - /^update[0-9]{2}x/         
script:
  - ./steeltoe-ci/scripts/travis_install.sh
  - ./steeltoe-ci/scripts/travis_build.sh
  - ./steeltoe-ci/scripts/travis_test.sh
before_install:
  - git clone https://github.com/SteeltoeOSS/steeltoe-ci.git -v
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 1024; fi
